version: '3'

services:
  streamlit:
    container_name: streamlit_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8501:8501"
    build: .
    command: bash entrypoint.sh
