version: '3.8'

services:
  streamlit:
    container_name: streamlit_app
    restart: always
    expose:
      - "8501"
    ports:
      - "8501:8501"
    build: .
    command: bash entrypoint.sh

  nginx:
    restart: always
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /home/ubuntu/ssl:/etc/ssl  # hard-coded for now
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
