[server]
# maxUploadSize = 12000
maxUploadSize = 2000

# maxMessageSize = 12000
maxMessageSize = 2000

[browser]
gatherUsageStats = false

[theme]
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#000000"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#EA3423"  # original BBDO red
# secondaryBackgroundColor = "#C0749C"  # Rep Score light purple
# secondaryBackgroundColor = "#683474"  # Rep Score dark purple
# secondaryBackgroundColor = "#F89C84"  # Rep Score orange
# secondaryBackgroundColor = "#FFD4B4"  # Rep Score tan

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
#font =
